apiVersion: v1
kind: Secret
metadata:
    name: homarr-oauth
    namespace: apps
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:LY/1zCSWL7UQVxwuUsB7BUPfnH08+v39oAy4rZtfAUu0V+ipV+jJdA==,iv:66uVbvKRb7qEzLdf5w2Mv0ReuW32cZOLdVMFheB4AEE=,tag:/v9PsjCkZYUruaGbwZRoSA==,type:str]
    client-secret: ENC[AES256_GCM,data:pKEwmgaYRHYu9y/RdA1gkStCRvi7wkufZuKKXpDscm6qHNdJUbPPn/uLCOA71IzCTWWo5sNXw0gAbIVsIUBzBWdhHC03gFMqj2IT2mci+MWVXsmbFkttgo0p4z+e6b/4+0t1xQeq9f56qq4Ya0UZSSHBdzsaD6T0tvn5INZ7YR0=,iv:FXGnk5xtYxqFHBvmuwEsc2fO7uw1Q0M4rutl5IryI3E=,tag:jdMzY64xMWL77mfxDWr3Xw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lsvwl2p2u3977vs0jm9cd28dgdm4ey8u8qwe6zxz3q45szc0u5vq7hn57y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcHUvL0lrdDF3bDhYOXp1
            U1FzcVhFSzh6ZXVkRnZzSUlwd2ROYk9UM3lVCmpaTDRDRHRYS2NNZXplZU05MWox
            eDRNTFhNZG1pSEVzcHRIQ1A4NXVPZGcKLS0tIFNGL1IvYWpscnRJN2pnSHlPTnVn
            OTdVdDRuQVlndFVrbllyYWo2dnc0ZFkK0m25ZR1U+LUn1JKAV4TVx3UDRhCUIHsD
            PPrH3O9JdNQ09YEk++cpnLUWCZ8g7PotYnL9Y/iREYk1GFBL8Natuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-18T10:15:06Z"
    mac: ENC[AES256_GCM,data:tmAh1Q3alquYNyAFl2wrlHPq4Vu937fCi/jCavS1m7y+HfgEQZxp7T6dWLll/aR22bIwDWSBpAXCPIKf5Xl24vwe3auaWUZwX6VX/nIb8lGklLMUxfj4ozAqCefTud0FIWQUs/K3sz2IEkaw9l+ZUX4PYpA3Kb5fwlKWHOzgfV0=,iv:l0UesRyp1TIcNrUSv6mWorWy/fM96KCtL+/u2Oo/Ecw=,tag:jH+kL0Grrwtu2FfSBB9Ewg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
