
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dashy
  namespace: apps
spec:
  chart:
    spec:
      chart: dashy
      sourceRef:
        kind: HelmRepository
        name: selfhosted-helmcharts
        namespace: apps
      version: 0.1.8
  interval: 1h
  values:
    static:
      enabled: false
    volumes:
      - name: dashy-volume
        persistentVolumeClaim:
          claimName: dashy-pvc
    volumeMounts:
      - name: dashy-volume
        mountPath: /app/user-data/
    ingress:
      enabled: true
      className: "traefik"
      annotations:
        kubernetes.io/ingress.class: "traefik"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: dashy.homelab.haseebmajid.dev
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - dashy.homelab.haseebmajid.dev
          secretName: dashy-haseebmajid-dev-tls
