apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: apps
spec:
  chart:
    spec:
      chart: home-assistant
      sourceRef:
        kind: HelmRepository
        name: pajikos
        namespace: apps
      version: 0.2.60
  interval: 1h
  values:
    configuration:
      enabled: true
      forceInit: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        # traefik.ingress.kubernetes.io/router.middlewares: "auth-ak-outpost-authentik-embedded-outpost@kubernetescrd"
      hosts:
        - host: home.homelab.haseebmajid.dev
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - home.homelab.haseebmajid.dev
          secretName: home-haseebmajid-dev-tls
    securityContext:
      privileged: true
    podSecurityContext:
      capabilities:
        add:
          - NET_ADMIN
          - NET_RAW
          - NET_BROADCAST
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: "longhorn"
    additionalVolumes:
      - hostPath:
          path: >-
            /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_94923f9c55a4ed11abf188582981d5c7-if00-port0
          type: CharDevice
        name: usb
    additionalMounts:
      - mountPath: /dev/ttyACM0
        name: usb
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - um790
