apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: gitlab
type: Opaque
stringData:
    accesskey: ENC[AES256_GCM,data:8FrSh3HEaxjqB4LDKib5xJfbowA=,iv:1SS1CndAuBzBbRF7x11nCwzo9lyevZh/ItWIkW2fjYo=,tag:LpekrooY7MPDTSk4gSl4zw==,type:str]
    secretkey: ENC[AES256_GCM,data:q9VwB7RBn/THap7EdPyjZRfFQIh5d764ieGIIExFAXm7/3i5LYLwIg==,iv:hkPx/pFrxaeUXsnrzvkcfNix4ewO2YEi2Btsx5gZOdQ=,tag:EEHxOrzI18nXRnsM0geRMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lsvwl2p2u3977vs0jm9cd28dgdm4ey8u8qwe6zxz3q45szc0u5vq7hn57y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUE50ZUVSYXdxOU8wWkl3
            RVB3cUJVWEV4OXJPRy9HWmNwYkR0Nk4vMFNNCnpqeFFzSUl1dVVxSFdya21SR3c5
            WHcvdHZJdmNpWUhUZ3Bya3pWQklZdXMKLS0tIE1lQlJPVjVhQUM3UzlHQlFDQjRO
            OU1yWG50ZjFMNXg5YnVvZmIrank3RVEKkUQ1DKToLbuOkRRoZ2X3X6fohMqcapDu
            8MCVpUVm7RxPwO/QIjEgFyIaA3PBWO3cQhOPr1nveCiRzUdd+Iliwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-02T06:59:33Z"
    mac: ENC[AES256_GCM,data:GsEAEUZ2CYjhdvbeysqfBsIuisfpRVu557NUTSokE2KfGdCnSoGgTtm0GCUMpeYoBT0Qijht5StULB4NJIWLfCmJl2vihN8pM/OjcQ4o2wC+lKbSk0ZR/bqOZ7EejYo6V54L0uOANOutBEHDbk+RziuaTP8oaHnyUmsDq233cig=,iv:rbU0q6KHqRzzcwP5d+RrJvafHs3RUuuEVoabn90PXGI=,tag:JkoindWqdDEmmoFumJc/Bw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
