apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secret
  namespace: gitlab
type: Opaque
stringData:
  runner-registration-token: ENC[AES256_GCM,data:+FqnLWwKXVSl5CowxLIM/ACWxZLpYw9Uxb8g,iv:erMW+52UBLon5gZgZ1hh2yX1HEvqUkBB5Rz8iycr0Vo=,tag:CRL9BjSkqT36yes9f5zQ4A==,type:str]
  runner-token: ENC[AES256_GCM,data:PbNKzagTw7zugNMnQH92AkUrxBZNQ2MBfg==,iv:SkYbDu9pn6jeIoHCG5+e99+1vrgepZzXa85rniDuKw4=,tag:qhl5UPSLmOIFbfhHJjUxZg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1lsvwl2p2u3977vs0jm9cd28dgdm4ey8u8qwe6zxz3q45szc0u5vq7hn57y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dlZwek5ScndZMGxvVFRq
        UTdGVWJKMWlRVElBc1pML1JBdUxZZGEyUlRBCnNuZjVuNTVTUEM4blRoVzZRckFJ
        OENGTVRwK0F6RmwzWFpKT09TWWROU3cKLS0tIGxHZ0tlR0RubStNOUhGVGNXdlVx
        UGxIY2VEdisvZVhlcGpLa253MTUrQzQKP+qccYb0vGoaosQ/mSZOaWeIout6WwAr
        7q/Wg8WEGIsBK2RGllK4HXsH9Sd8lk97tSKiCMm1r3SNp6tbErnJhw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-06-05T21:32:38Z"
  mac: ENC[AES256_GCM,data:zCTZvtcAvkJrwNG76F+12YmXmiCQEaOZCyhslqPBu1aiwW8AiXc3lCr6bJjxiNazYrtJOmX7n23WUA+ycyKQJij5bCGe2xL2N6Fpxp59yjOeWUo2izXkz8CJmXC3POjKHs+/RAC3mAEqpT9UtVmGF6uEXc2BUeCD6kql3vdQIp4=,iv:EcS4AlykbywcpQuoHoPSbi04PhaY/nnSxlT7H9CFC6k=,tag:WuhERgx0wnBa0BzPe/XwpQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
